# Code Generated by Sidekick is for learning and experimentation purposes only.
import re
import random
import datetime as dt

import numpy as np
import gradio as gr
from better_profanity import profanity

profanity.load_censor_words()

ABUSIVE_PATTERNS = [
    r"\b(kill yourself|kys)\b",
    r"\b(i will kill|i'll kill)\b",
    r"\b(rape|raping)\b",
    r"\b(nazi)\b",
    r"\b(hate you|die)\b",
]
SEXUAL_EXPLICIT_PATTERNS = [
    r"\b(blowjob|handjob|porn|nudes|sex chat)\b",
]
SAFE_REFUSAL = "I can’t help with abusive/explicit content. Say it cleanly and I’ll help."

def is_blocked(text: str) -> bool:
    t = text.lower()
    if profanity.contains_profanity(t):
        return True
    for pat in ABUSIVE_PATTERNS + SEXUAL_EXPLICIT_PATTERNS:
        if re.search(pat, t, flags=re.I):
            return True
    return False

def _tone(sr, freq, dur, vol=0.15):
    t = np.linspace(0, dur, int(sr * dur), endpoint=False)
    return (vol * np.sin(2 * np.pi * freq * t)).astype(np.float32)

def make_beep():
    sr = 22050
    y = _tone(sr, 880, 0.10, 0.12)
    return (sr, y)

def make_faah_synth():
    sr = 22050
    dur = 0.28
    t = np.linspace(0, dur, int(sr * dur), endpoint=False)

    f0, f1 = 650, 170
    freq = f0 * (f1 / f0) ** (t / dur)
    phase = 2 * np.pi * np.cumsum(freq) / sr
    sweep = np.sin(phase).astype(np.float32)

    noise = (np.random.randn(len(t)).astype(np.float32)) * 0.08
    env = np.exp(-8 * t).astype(np.float32)

    y = (0.9 * sweep + noise) * env
    y = np.tanh(2.2 * y).astype(np.float32)
    return (sr, y)

HINGLISH_PHRASES = {
    "kya scene": "What’s the plan / what’s going on?",
    "scene kya hai": "What’s the status?",
    "kya chal raha": "What’s up?",
    "kya haal": "How are things?",
    "chill maar": "Relax / don’t stress.",
    "set hai": "Confirmed / fixed.",
    "kal set": "Let’s do it tomorrow.",
    "jugaad": "Quick workaround / hack.",
    "chalta hai": "It’s fine / let it slide.",
    "timepass": "Killing time / low-stakes fun.",
}

GENZ_SLANG = {
    "aura": "Your vibe/energy; ‘aura points’ = cool points.",
    "cooked": "Exhausted / overwhelmed / done for.",
    "brainrot": "Scroll-fried meme brain vibe.",
    "delulu": "Playfully delusional (optimistic coping).",
    "rizz": "Charisma / flirting skill.",
    "cap": "Lie/exaggeration. ‘No cap’ = for real.",
    "bet": "Okay / agreed / say less.",
    "mid": "Mediocre.",
    "tea": "Gossip / truth / info.",
    "yap": "Talk a lot (playful).",
}

TOPIC_KEYS = {
    "plans": {"plan","weekend","tomorrow","today","hangout","meet","movie","cafe"},
    "relationships": {"crush","date","dating","ghost","seen","reply","situationship"},
    "study": {"exam","test","assignment","class","study","notes"},
    "food": {"momos","chai","coffee","pizza","burger","snack","craving","food"},
    "gym": {"gym","workout","protein","leg day","cardio"},
    "social": {"reel","story","post","caption","soft launch","hard launch","instagram"},
    "gaming": {"game","rank","match","lag","carry","win"},
    "mood": {"sad","tired","stressed","anxious","overthinking","burnt","low"},
}

def detect_topic(text: str) -> str:
    tokens = set(re.findall(r"[a-z']+", text.lower()))
    best = ("general", 0)
    for topic, keys in TOPIC_KEYS.items():
        score = len(tokens & keys)
        if score > best[1]:
            best = (topic, score)
    return best[0]

def hashtags(topic: str) -> str:
    base = {
        "plans": ["#weekendplans", "#friends", "#hangout"],
        "relationships": ["#situationship", "#texting", "#iykyk"],
        "study": ["#studentlife", "#examseason", "#studygram"],
        "food": ["#foodie", "#snacktime", "#streetfood"],
        "gym": ["#gymarc", "#fitness", "#legday"],
        "social": ["#reels", "#memes", "#captionideas"],
        "gaming": ["#gaming", "#ranked", "#gg"],
        "mood": ["#mood", "#relatable", "#selfcare"],
        "general": ["#relatable", "#memes", "#vibes"],
    }
    return " ".join(base.get(topic, base["general"])[:5])

def make_caption(core: str, topic: str) -> str:
    hooks = ["POV:", "Me:", "Lowkey", "Highkey", "It’s giving", "Normalize"]
    specifics = ["at 2:13am", "with 3% battery", "after one chai", "during exam week", "in the group chat"]
    prompts = ["Real or nah.", "IYKYK.", "Be honest.", "Tell me I’m not alone."]
    core = re.sub(r"\s+", " ", core).strip()
    core = core[:90] if core else "this whole situation"
    return f"{random.choice(hooks)} {core} {random.choice(specifics)} {random.choice(prompts)}\n{hashtags(topic)}"

def make_faah_meme_text(core: str) -> str:
    core = re.sub(r"\s+", " ", core).strip() or "I try a tiny shortcut"
    setups = [f"Me: {core}", f"POV: {core}", f"When {core}"]
    payoff = random.choice([
        "Reality: *FAAAH* (instant consequences)",
        "Universe: *FAAH* (same-day delivery)",
        "My luck: *FAAH* (plot twist unlocked)",
    ])
    return f"{random.choice(setups)}\n{payoff}"

def slang_lookup(term: str) -> str:
    key = term.strip().lower()
    if not key:
        return "Use: /slang <word>  (e.g., /slang cooked)"
    if key in GENZ_SLANG:
        return f"{key}: {GENZ_SLANG[key]}"
    if key in ("no cap", "nocap"):
        return "no cap: For real / not lying."
    return "Not in my slang list yet—try another word."

def hinglish_lookup(term: str) -> str:
    key = term.strip().lower()
    if not key:
        return "Use: /hindi <phrase>  (e.g., /hindi kya scene)"
    hits = []
    for k, v in HINGLISH_PHRASES.items():
        if key in k:
            hits.append((k, v))
    if not hits:
        return "Not found—try shorter (e.g., ‘scene’, ‘set’, ‘jugaad’)."
    return "\n".join([f"{k}: {v}" for k, v in hits[:10]])

def friendly_chat(user_text: str, topic: str) -> str:
    low = user_text.lower().strip()
    if low.startswith("/slang"):
        return slang_lookup(user_text[len("/slang"):])
    if low.startswith("/hindi"):
        return hinglish_lookup(user_text[len("/hindi"):])
    if low.startswith("/caption"):
        return make_caption(user_text[len("/caption"):].strip(), topic)
    if low.startswith("/meme"):
        core = user_text[len("/meme"):].strip()
        if "faah" in core.lower():
            core2 = re.sub(r"\bfaah\b", "", core, flags=re.I).strip()
            return "FAAH meme (text):\n" + make_faah_meme_text(core2)
        return "Meme idea:\n" + make_caption(core, topic)

    if "faah" in low:
        core2 = re.sub(r"\bfaah\b", "", user_text, flags=re.I).strip()
        return "FAAH meme (text):\n" + make_faah_meme_text(core2)

    openers = {
        "plans": ["Weekend ka scene kya hai?", "Plan drop kar—time lock karo."],
        "relationships": ["Real talk: clarity ya peace?", "Seen zone ka update?"],
        "study": ["30-min sprint? bas start.", "Chai + notes = power-up."],
        "food": ["Craving detected. Momos ya chai?", "Spicy vs regret—choose."],
        "gym": ["Gym arc loading—leg day pe vanish mat."],
        "social": ["Soft launch ya hard launch?", "Caption chahiye? bol."],
        "gaming": ["Warm-up then ranked.", "Clean comms = W."],
        "mood": ["Vibe check: 0–10?", "Chill maar—1 small step first."],
        "general": ["Bol, kya scene?", "Give me the lore."],
    }
    s = random.choice(openers.get(topic, openers["general"]))
    if random.random() < 0.25:
        s += " (chai = therapy)"
    return s

def respond(user_msg, history, state, sound_mode):
    history = history or []
    state = state or {"name": None, "last_topic": "general", "last_seen_at": None}

    if is_blocked(user_msg):
        history = history + [(user_msg, SAFE_REFUSAL)]
        audio = make_beep() if sound_mode != "Off" else None
        return history, state, audio

    topic = detect_topic(user_msg)
    state["last_topic"] = topic
    state["last_seen_at"] = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    reply = friendly_chat(user_msg, topic)
    history = history + [(user_msg, reply)]

    if sound_mode == "Off":
        audio = None
    elif sound_mode == "FAAH synth" and ("faah" in user_msg.lower()):
        audio = make_faah_synth()
    else:
        audio = make_beep()

    return history, state, audio

def reset():
    return [], {"name": None, "last_topic": "general", "last_seen_at": None}, None

with gr.Blocks(title="Gen‑Z Hinglish Meme Bot (Safe + Sound)") as demo:
    gr.Markdown(
        "## Gen‑Z Hinglish Meme Bot (safe + FAAH + sound)\n"
        "Commands: /meme ... | /caption ... | /slang ... | /hindi ...\n"
        "FAAH sound plays when message contains **faah** and Sound mode = FAAH synth."
    )
    state = gr.State({"name": None, "last_topic": "general", "last_seen_at": None})
    chatbox = gr.Chatbot(height=420, label="Chat")
    audio = gr.Audio(label="Sound", autoplay=True)
    sound_mode = gr.Radio(["Off", "Beep", "FAAH synth"], value="FAAH synth", label="Sound mode")
    msg = gr.Textbox(label="Type here", placeholder="Try: /meme faah about skipping gym")

    with gr.Row():
        send = gr.Button("Send")
        clear = gr.Button("Reset")

    send.click(respond, inputs=[msg, chatbox, state, sound_mode], outputs=[chatbox, state, audio])
    msg.submit(respond, inputs=[msg, chatbox, state, sound_mode], outputs=[chatbox, state, audio])
    clear.click(reset, inputs=None, outputs=[chatbox, state, audio])

demo.launch()
