# Code Generated by Sidekick is for learning and experimentation purposes only.
import base64
import datetime as dt
import io
import math
import random
import re
import wave

import streamlit as st
import streamlit.components.v1 as components

# =============================
# Config
# =============================
st.set_page_config(page_title="Office Chatbot (FAAH + Celebrate)", layout="centered")
random.seed()

# =============================
# UI (dark bg + readable glass surfaces)
# =============================
st.markdown(
    """
<style>
/* Code Generated by Sidekick is for learning and experimentation purposes only. */
.stApp{
  background:
    radial-gradient(900px 520px at 12% 8%, rgba(98,181,229,0.22), transparent 60%),
    radial-gradient(800px 520px at 92% 12%, rgba(134,188,37,0.18), transparent 62%),
    radial-gradient(800px 520px at 50% 92%, rgba(255,209,0,0.10), transparent 62%),
    linear-gradient(180deg, #0B1220 0%, #0A0F16 65%, #0B1220 100%);
}
:root{
  --ink:#0B1220;
  --muted:#4B5563;
  --line:rgba(11,18,32,.10);
  --glass:rgba(255,255,255,.92);
  --glass2:rgba(255,255,255,.80);
  --shadow: 0 14px 46px rgba(0,0,0,.22);
}
.block-container{ padding-top: 1.1rem; max-width: 980px; }

.hero{
  border: 1px solid var(--line);
  background: var(--glass);
  border-radius: 18px;
  padding: 14px 16px 12px 16px;
  box-shadow: var(--shadow);
  backdrop-filter: blur(10px);
}
.title{ font-size: 1.45rem; font-weight: 900; margin:0; color: var(--ink) !important; }
.sub{ margin-top: 6px; font-size: .95rem; color: var(--muted) !important; }
.kbd{
  display:inline-block; padding: 2px 8px; border-radius: 10px;
  border: 1px solid var(--line); background: rgba(255,255,255,.70);
  font-size: .84rem; margin-right: 6px; color: var(--ink) !important;
}

.card{
  margin-top: 12px;
  border: 1px solid var(--line);
  background: var(--glass2);
  border-radius: 18px;
  padding: 12px 12px 8px 12px;
  box-shadow: var(--shadow);
  backdrop-filter: blur(10px);
}
.small{ font-size:.90rem; color: var(--muted) !important; }

section[data-testid="stSidebar"]{
  background: rgba(255,255,255,.86) !important;
  border-right: 1px solid var(--line);
  backdrop-filter: blur(10px);
}

div[data-testid="stChatMessage"]{
  border: 1px solid var(--line) !important;
  background: rgba(255,255,255,.92) !important;
  border-radius: 16px !important;
  box-shadow: 0 10px 28px rgba(0,0,0,.12);
}
div[data-testid="stChatMessage"] *{ color: var(--ink) !important; }

div[data-testid="stChatInput"]{
  border: 1px solid var(--line) !important;
  border-radius: 14px !important;
  background: rgba(255,255,255,.92) !important;
  box-shadow: 0 10px 28px rgba(0,0,0,.12);
}
div[data-testid="stChatInput"] textarea{ color: var(--ink) !important; }
</style>
""",
    unsafe_allow_html=True,
)

# =============================
# State
# =============================
def ss_init():
    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "sound_enabled" not in st.session_state:
        st.session_state.sound_enabled = False
    if "pending_audio" not in st.session_state:
        st.session_state.pending_audio = None  # {bytes,mime,label,autoplay,nonce}
    if "audio_nonce" not in st.session_state:
        st.session_state.audio_nonce = 0
    if "faah_upload_bytes" not in st.session_state:
        st.session_state.faah_upload_bytes = None
        st.session_state.faah_upload_mime = None
        st.session_state.faah_upload_name = None
    if "_queued_input" not in st.session_state:
        st.session_state._queued_input = None
    if "pending_fx" not in st.session_state:
        st.session_state.pending_fx = None  # "balloons" | "snow" | "fire"
    if "pending_toast" not in st.session_state:
        st.session_state.pending_toast = None

ss_init()

# =============================
# Audio helpers (FAAH upload + synth fallback)
# =============================
DEFAULT_SOUND_ERROR = "Autoplay blocked. Click ‘Enable Sound’ once, then trigger again."

def _to_wav_bytes(sr: int, samples_f32: list[float]) -> bytes:
    pcm = bytearray()
    for x in samples_f32:
        x = max(-1.0, min(1.0, float(x)))
        i = int(x * 32767.0)
        pcm += int(i).to_bytes(2, "little", signed=True)
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sr)
        wf.writeframes(bytes(pcm))
    return buf.getvalue()

def make_faah_synth_wav() -> bytes:
    sr, dur = 22050, 0.26
    n = int(sr * dur)
    out = []
    f0, f1 = 760.0, 150.0
    phase = 0.0
    for i in range(n):
        t = i / sr
        freq = f0 * ((f1 / f0) ** (t / dur))
        phase += (2.0 * math.pi * freq) / sr
        sweep = math.sin(phase)
        noise = (random.random() * 2.0 - 1.0) * 0.09
        env = math.exp(-8.5 * t)
        out.append(math.tanh(2.2 * (0.92 * sweep + noise)) * env)
    return _to_wav_bytes(sr, out)

def get_faah_bytes() -> tuple[bytes, str, str]:
    if st.session_state.faah_upload_bytes:
        return (
            st.session_state.faah_upload_bytes,
            st.session_state.faah_upload_mime or "audio/mpeg",
            f"FAAH (uploaded: {st.session_state.faah_upload_name})",
        )
    return (make_faah_synth_wav(), "audio/wav", "FAAH (synth)")

def queue_audio(bytes_data: bytes, mime: str, label: str, autoplay: bool):
    st.session_state.audio_nonce += 1
    st.session_state.pending_audio = {
        "bytes": bytes_data,
        "mime": mime,
        "label": label,
        "autoplay": autoplay,
        "nonce": st.session_state.audio_nonce,
    }

def render_autoplay_audio(audio_bytes: bytes, mime: str, nonce: int):
    b64 = base64.b64encode(audio_bytes).decode("ascii")
    html = f"""
    <audio id="faah{nonce}" autoplay>
      <source src="data:{mime};base64,{b64}" type="{mime}">
    </audio>
    <script>
      (function(){{
        const el = document.getElementById("faah{nonce}");
        if(!el) return;
        const p = el.play();
        if(p && p.catch) p.catch(()=>{{}});
      }})();
    </script>
    """
    components.html(html, height=0, width=0)

# =============================
# FAAH triggers (corporate pain points)
# =============================
TRIGGERS_LOW = [
    r"\bclient\b.*\bnew ideas?\b",
    r"\bclient\b.*\bmore ideas?\b",
    r"\bclient\b.*\bbrainstorm\b",
    r"\bclient\b.*\bfresh ideas?\b",
    r"\bclient\b.*\binnovate\b",
]
TRIGGERS_MED = TRIGGERS_LOW + [
    r"\bsmall change\b",
    r"\bquick deck\b",
    r"\bby eod\b|\beod\b",
    r"\basap\b",
    r"\bquick call\b|\bhop on\b.*\bcall\b",
    r"\brebaseline\b",
    r"\bscope change\b|\bchange request\b",
    r"\bkeep it simple\b.*\bimpactful\b",
]
TRIGGERS_HIGH = TRIGGERS_MED + [
    r"\bcircle back\b",
    r"\bsynergy\b",
    r"\bvalue add\b|\bvalue-add\b",
    r"\blow effort\b.*\bhigh impact\b",
    r"\bone last thing\b",
    r"\bpls fix\b|\bplz fix\b|\bplease fix\b",
    r"\bdeck\b.*\btonight\b",
    r"\bclient\b.*\bnew requirement\b",
    r"\bmake it pop\b",
]

def should_play_faah(text: str, sensitivity: str) -> bool:
    t = (text or "").lower().strip()
    patterns = TRIGGERS_LOW if sensitivity == "Low" else TRIGGERS_MED if sensitivity == "Medium" else TRIGGERS_HIGH
    return any(re.search(p, t) for p in patterns)

# =============================
# Celebrate triggers (good news)
# =============================
GOOD_NEWS_PATTERNS = [
    r"\bgood news\b",
    r"\bwe won\b|\bwe won the\b",
    r"\bapproved\b|\bapproval\b|\bgreen light\b",
    r"\bsigned\b|\bcontract signed\b|\bpo issued\b",
    r"\bgo[- ]live\b|\blaunch(ed)?\b",
    r"\bkudos\b|\bshoutout\b|\bappreciation\b",
    r"\bpromotion\b|\bincrement\b|\braise\b",
    r"\bclient loved\b|\bclient happy\b|\bpositive feedback\b",
    r"\bpassed\b.*\buat\b|\buat passed\b",
]

def is_good_news(text: str) -> bool:
    t = (text or "").lower().strip()
    return any(re.search(p, t) for p in GOOD_NEWS_PATTERNS)

# =============================
# Corporate Hinglish jokes (light)
# =============================
FAAH_QUIPS = [
    "FAAH. ‘Small change’ ka matlab: full redesign, bas emotionally.",
    "FAAH. Client ne bola ‘quick deck’—calendar ne bola ‘good luck’.",
    "FAAH. ‘EOD’ is a feeling, not a time. Yaar.",
    "FAAH. ‘Keep it simple’ + ‘make it impactful’ = do bosses, one brain.",
    "FAAH. ‘Quick call’ = 5 mins + 43 mins of “context setting”.",
    "FAAH. ‘Circle back’ = round-trip ticket to nowhere, bhai.",
    "FAAH. ‘Low effort, high impact’—haan, like magic.",
    "FAAH. ‘One last thing’—aur phir last ke 7 cousins aate hain.",
    "FAAH. ‘Make it pop’—PowerPoint bhi therapist maang raha hai.",
    "FAAH. ‘New ideas’ with same budget—innovation ka jugaad edition.",
]
GOOD_NEWS_QUIPS = [
    "W. Aaj toh deliverable ne smile diya. Shabaash.",
    "Client happy? Matlab universe thoda balance mein hai.",
    "Green light mil gaya—ab bas scope ko green mat kar dena.",
    "UAT passed? Party nahi, but ek chai toh banti hai.",
]
TINY_NORMAL_QUIPS = [
    "Noted—clean, crisp, client-safe.",
    "Got it. We’ll keep it short and usable.",
    "Okay. No drama, only deliverables.",
    "Done. We’ll align, then execute.",
]

# =============================
# Office response engine
# =============================
def office_reply(user_text: str, faah_hit: bool, good_hit: bool) -> str:
    t = (user_text or "").strip()
    low = t.lower()

    if low == "/help":
        return (
            "Commands:\n"
            "- /faah (play FAAH)\n"
            "- /triggers (show what triggers FAAH)\n"
            "- /help\n\n"
            "Ask for: email / standup / agenda / RAID / notes / slides / workplan."
        )
    if low == "/triggers":
        return "FAAH triggers (by sensitivity): client new ideas, small change, quick deck, EOD/ASAP, quick call, circle back, make it pop."
    if low == "/faah":
        return "FAAH triggered (manual)."

    if good_hit:
        return (
            f"{random.choice(GOOD_NEWS_QUIPS)}\n\n"
            "Want me to turn this into a client-safe update?\n"
            "Send: what happened + metric + next step + ask (if any). (Hinglish chalega)"
        )

    if any(k in low for k in ["standup", "status update", "daily update", "scrum"]):
        return (
            f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
            "Template:\nDone:\n- \n\nNext:\n- \n\nBlockers/Risks:\n- \n\nAsk (if any):\n- "
        )

    if any(k in low for k in ["email", "mail", "slack", "teams", "message"]):
        return (
            f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
            "Tell me: audience, ask, deadline, tone. Draft template:\n\n"
            "Subject: [Action] [Topic] by [Date]\n\n"
            "Hi [Name],\n"
            "Sharing a quick update on [topic].\n\n"
            "Status:\n- \n\n"
            "Next steps (Owner | Date):\n- \n\n"
            "Decision/ask:\n- \n\n"
            "Thanks,\n[Your name]"
        )

    if any(k in low for k in ["agenda", "meeting agenda"]):
        return (
            f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
            "30-min agenda:\n"
            "1) Outcomes (2)\n2) Progress (8)\n3) Decisions (8)\n4) Risks (6)\n5) Next steps (6)\n\n"
            "Share topic + attendees; I’ll tailor it."
        )

    if any(k in low for k in ["mom", "minutes", "meeting notes", "notes"]):
        return (
            f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
            "Meeting notes template:\nContext:\n- \n\nAttendees:\n- \n\nDecisions:\n- \n\nActions (Owner | Due | Item):\n- \n\nRisks/Issues:\n- "
        )

    if any(k in low for k in ["raid", "risk", "issue", "blocker", "dependency", "assumption"]):
        return (
            f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
            "RAID entry:\nType:\nDescription:\nImpact:\nLikelihood:\nOwner:\nMitigation:\nDue:\nStatus:\n\nPaste your sentence and I’ll format it."
        )

    if any(k in low for k in ["slides", "deck", "ppt", "storyline"]):
        return (
            f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
            "6-slide storyline:\n1) Context\n2) Current state\n3) Insights\n4) Options + trade-offs\n5) Recommendation\n6) Roadmap + risks\n\n"
            "Tell me audience + decision + time."
        )

    if any(k in low for k in ["workplan", "project plan", "timeline", "plan"]):
        return (
            f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
            "Workplan starter:\nW1 align\nW2 assess\nW3 options\nW4 recommend + roadmap\n\nTell me duration + deliverables."
        )

    if faah_hit:
        return (
            f"{random.choice(FAAH_QUIPS)}\n\n"
            "Client-ready idea structure (fast):\n"
            "A) Optimize (low risk)\nB) Enable (medium)\nC) Transform (bold)\n\n"
            "Bas 3 inputs do: objective, constraints, and decision-maker."
        )

    return (
        f"{random.choice(TINY_NORMAL_QUIPS)}\n\n"
        "Tell me: email / standup / agenda / RAID / notes / slides / workplan. Paste rough text; I’ll rewrite it cleanly."
    )

# =============================
# Sidebar controls
# =============================
with st.sidebar:
    st.subheader("FAAH sound")
    up = st.file_uploader("Upload faah.mp3 or faah.wav", type=["mp3", "wav"])
    if up is not None:
        st.session_state.faah_upload_bytes = up.getvalue()
        st.session_state.faah_upload_name = up.name
        st.session_state.faah_upload_mime = up.type or ("audio/mpeg" if up.name.lower().endswith(".mp3") else "audio/wav")
        st.success(f"Loaded: {up.name}")

    attempt_autoplay = st.toggle("Attempt autoplay", value=True)
    if st.button("Enable Sound (click once)"):
        st.session_state.sound_enabled = True
        st.success("Sound enabled.")

    sensitivity = st.selectbox("FAAH sensitivity", ["Low", "Medium", "High"], index=2)

    st.divider()
    st.subheader("Celebrate FX (good news)")
    celebrate_fx = st.radio("Effect", ["Balloons", "Snow (sprinkle)", "Fire toast only", "Off"], index=0)
    st.caption("Triggers on ‘good news’, ‘approved’, ‘we won’, ‘go-live’, etc.")

    st.divider()
    st.subheader("Shortcuts")
    if st.button("Client wants new ideas by EOD (FAAH)"):
        st.session_state._queued_input = "Client is asking for new ideas by EOD, same budget."
    if st.button("‘Small change’ make it pop (FAAH)"):
        st.session_state._queued_input = "It’s a small change, just make it pop."
    if st.button("Good news: approved (Celebrate)"):
        st.session_state._queued_input = "Good news! Client approved the approach."
    if st.button("Draft client email"):
        st.session_state._queued_input = "Draft an email to the client with status and next steps."
    if st.button("Standup update"):
        st.session_state._queued_input = "Help me write a standup update."
    if st.button("Play FAAH now"):
        st.session_state._queued_input = "/faah"

# =============================
# Header
# =============================
st.markdown(
    """
<div class="hero">
  <div class="title">Office Chatbot (Hinglish) • FAAH + Sprinkle</div>
  <div class="sub">
    FAAH triggers on corporate pain (new ideas / EOD / small change / quick call).
    Celebrate triggers on good news (approved / we won / go-live).
    <br><br>
    <span class="kbd">Try:</span>
    <span class="kbd">Client wants new ideas by EOD</span>
    <span class="kbd">Good news: approved</span>
    <span class="kbd">Draft an email</span>
  </div>
</div>
""",
    unsafe_allow_html=True,
)

# =============================
# Render pending FX (runs before chat)
# =============================
if st.session_state.pending_toast:
    st.toast(st.session_state.pending_toast)
    st.session_state.pending_toast = None

if st.session_state.pending_fx == "balloons":
    st.balloons()
    st.session_state.pending_fx = None
elif st.session_state.pending_fx == "snow":
    st.snow()
    st.session_state.pending_fx = None
elif st.session_state.pending_fx == "fire":
    # "fire" is a toast (lightweight, always works)
    st.session_state.pending_fx = None

# =============================
# Render pending audio
# =============================
if st.session_state.pending_audio is not None:
    p = st.session_state.pending_audio
    st.caption(p["label"])
    if attempt_autoplay and p["autoplay"] and st.session_state.sound_enabled:
        render_autoplay_audio(p["bytes"], p["mime"], p["nonce"])
    st.audio(p["bytes"], format=p["mime"])
    st.session_state.pending_audio = None

# =============================
# Chat
# =============================
st.markdown('<div class="card">', unsafe_allow_html=True)
st.markdown('<div class="small">Tip: “Client wants new ideas by EOD” (FAAH). “Good news approved” (sprinkle/balloons).</div>', unsafe_allow_html=True)

for m in st.session_state.messages:
    with st.chat_message(m["role"]):
        st.markdown(m["content"])
        st.markdown(f'<div class="small">{m["ts"]}</div>', unsafe_allow_html=True)

queued = st.session_state.get("_queued_input")
if queued:
    st.session_state._queued_input = None

user_text = queued or st.chat_input("Type here…")
st.markdown("</div>", unsafe_allow_html=True)

# =============================
# Handle message
# =============================
if user_text:
    ts = dt.datetime.now().strftime("%H:%M")
    st.session_state.messages.append({"role": "user", "content": user_text, "ts": ts})

    faah_hit = (user_text.strip().lower() == "/faah") or should_play_faah(user_text, sensitivity)
    good_hit = is_good_news(user_text)

    reply = office_reply(user_text, faah_hit=faah_hit, good_hit=good_hit)
    st.session_state.messages.append({"role": "assistant", "content": reply, "ts": ts})

    # FX for good news
    if good_hit and celebrate_fx != "Off":
        if celebrate_fx == "Balloons":
            st.session_state.pending_fx = "balloons"
            st.session_state.pending_toast = "🔥 Big W. Approved / go-live vibes."
        elif celebrate_fx.startswith("Snow"):
            st.session_state.pending_fx = "snow"
            st.session_state.pending_toast = "✨ Sprinkle time. Good news locked."
        elif celebrate_fx.startswith("Fire"):
            st.session_state.pending_fx = "fire"
            st.session_state.pending_toast = "🔥 Fire. Good news just dropped."

    # FAAH sound (only on pain triggers / manual)
    if faah_hit:
        if attempt_autoplay and (not st.session_state.sound_enabled):
            st.warning(DEFAULT_SOUND_ERROR)
        b, m, label = get_faah_bytes()
        queue_audio(b, m, label=label, autoplay=attempt_autoplay)

    st.rerun()
