# Code Generated by Sidekick is for learning and experimentation purposes only.
import base64
import datetime as dt
import io
import random
import re
import wave
from pathlib import Path

import numpy as np
import streamlit as st
import streamlit.components.v1 as components
from better_profanity import profanity

# =============================
# Config
# =============================
st.set_page_config(page_title="FAAH • Insta Meme Bot", page_icon=None, layout="centered")
profanity.load_censor_words()
random.seed()

# =============================
# Session state
# =============================
def _ss_init():
    if "messages" not in st.session_state:
        st.session_state.messages = []

    if "faah_upload_bytes" not in st.session_state:
        st.session_state.faah_upload_bytes = None
        st.session_state.faah_upload_mime = None
        st.session_state.faah_upload_name = None

    if "pending_audio_bytes" not in st.session_state:
        st.session_state.pending_audio_bytes = None
        st.session_state.pending_audio_mime = None
        st.session_state.pending_audio_label = None
        st.session_state.pending_audio_autoplay = True
        st.session_state.audio_nonce = 0

    if "sound_enabled" not in st.session_state:
        st.session_state.sound_enabled = False

    if "sound_error_once" not in st.session_state:
        st.session_state.sound_error_once = False

    if "_queued_input" not in st.session_state:
        st.session_state._queued_input = None


_ss_init()

# =============================
# Bright, colorful, aesthetic UI
# =============================
st.markdown(
    """
<style>
/* Code Generated by Sidekick is for learning and experimentation purposes only. */
:root{
  --bg0:#07080C;
  --card: rgba(255,255,255,0.06);
  --card2: rgba(255,255,255,0.09);
  --line: rgba(187,189,191,0.18);
  --txt: rgba(255,255,255,0.92);
  --muted: rgba(255,255,255,0.72);
}

.stApp{
  background:
    radial-gradient(1100px 680px at 10% 5%, rgba(0,220,6,0.16), transparent 60%),
    radial-gradient(900px 520px at 92% 8%, rgba(0,169,224,0.20), transparent 62%),
    radial-gradient(900px 560px at 50% 98%, rgba(255,209,0,0.14), transparent 62%),
    radial-gradient(1000px 600px at 70% 70%, rgba(218,41,28,0.10), transparent 60%),
    linear-gradient(180deg, #05060A 0%, #0A0F16 55%, #05060A 100%);
}

.block-container{
  padding-top: 1.25rem;
  max-width: 980px;
}

.hero{
  border: 1px solid var(--line);
  background: linear-gradient(180deg, rgba(255,255,255,0.08) 0%, rgba(255,255,255,0.04) 100%);
  border-radius: 18px;
  padding: 16px 16px 12px 16px;
  backdrop-filter: blur(10px);
}

.title{
  font-size: 1.55rem;
  font-weight: 800;
  color: var(--txt);
  letter-spacing: 0.2px;
  margin: 0;
}

.sub{
  margin-top: 6px;
  color: var(--muted);
  font-size: 0.95rem;
}

.kbd{
  display:inline-block;
  padding: 2px 8px;
  border-radius: 8px;
  border: 1px solid var(--line);
  background: rgba(255,255,255,0.06);
  font-size: 0.84rem;
  margin-right: 6px;
}

.chips{ display:flex; gap:8px; flex-wrap:wrap; margin-top:12px; }
.chip{
  border: 1px solid var(--line);
  background: rgba(255,255,255,0.06);
  padding: 7px 10px;
  border-radius: 999px;
  font-size: 0.86rem;
  color: var(--muted);
}

.card{
  margin-top: 12px;
  border: 1px solid var(--line);
  background: rgba(255,255,255,0.05);
  border-radius: 18px;
  padding: 12px 12px 6px 12px;
  backdrop-filter: blur(10px);
}

.small{
  opacity: 0.78;
  font-size: 0.90rem;
}

hr{
  border: none;
  height: 1px;
  background: var(--line);
  margin: 12px 0;
}

</style>
""",
    unsafe_allow_html=True,
)

# =============================
# Safety (clean-only)
# =============================
ABUSIVE_PATTERNS = [
    r"\b(kill yourself|kys)\b",
    r"\b(i will kill|i'll kill)\b",
    r"\b(rape|raping)\b",
    r"\b(nazi)\b",
    r"\b(hate you|die)\b",
]
SEXUAL_EXPLICIT_PATTERNS = [
    r"\b(blowjob|handjob|porn|nudes|sex chat)\b",
]
SAFE_REFUSAL = "I can’t help with abusive/explicit content. Say it cleanly and I’ll help."

def is_blocked(text: str) -> bool:
    t = (text or "").lower()
    if profanity.contains_profanity(t):
        return True
    for pat in ABUSIVE_PATTERNS + SEXUAL_EXPLICIT_PATTERNS:
        if re.search(pat, t, flags=re.I):
            return True
    return False

# =============================
# Audio helpers
# =============================
def _to_wav_bytes(sr: int, y: np.ndarray) -> bytes:
    y = np.clip(y, -1.0, 1.0)
    pcm = (y * 32767.0).astype(np.int16)
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sr)
        wf.writeframes(pcm.tobytes())
    return buf.getvalue()

def make_beep_wav() -> bytes:
    sr = 22050
    dur = 0.10
    t = np.linspace(0, dur, int(sr * dur), endpoint=False)
    y = 0.14 * np.sin(2 * np.pi * 880 * t)
    return _to_wav_bytes(sr, y.astype(np.float32))

def make_faah_synth_wav() -> bytes:
    sr = 22050
    dur = 0.28
    t = np.linspace(0, dur, int(sr * dur), endpoint=False)
    f0, f1 = 640, 160
    freq = f0 * (f1 / f0) ** (t / dur)
    phase = 2 * np.pi * np.cumsum(freq) / sr
    sweep = np.sin(phase).astype(np.float32)
    noise = (np.random.randn(len(t)).astype(np.float32)) * 0.08
    env = np.exp(-8 * t).astype(np.float32)
    y = (0.92 * sweep + noise) * env
    y = np.tanh(2.2 * y).astype(np.float32)
    return _to_wav_bytes(sr, y)

def load_assets_faah() -> tuple[bytes | None, str | None, str | None]:
    # Optional: if you keep assets/faah.mp3 in repo
    candidates = [
        (Path("assets/faah.mp3"), "audio/mpeg"),
        (Path("assets/faah.wav"), "audio/wav"),
    ]
    for p, mime in candidates:
        if p.exists() and p.is_file():
            return p.read_bytes(), mime, str(p)
    return None, None, None

ASSET_BYTES, ASSET_MIME, ASSET_PATH = load_assets_faah()

def queue_audio(bytes_data: bytes, mime: str, label: str | None = None, autoplay: bool = True):
    st.session_state.pending_audio_bytes = bytes_data
    st.session_state.pending_audio_mime = mime
    st.session_state.pending_audio_label = label
    st.session_state.pending_audio_autoplay = autoplay
    st.session_state.audio_nonce += 1

def render_autoplay_audio(audio_bytes: bytes, mime: str, nonce: int):
    # Best-effort autoplay via a fresh HTML audio element
    b64 = base64.b64encode(audio_bytes).decode("ascii")
    html = f"""
    <audio id="faah{nonce}" autoplay>
      <source src="data:{mime};base64,{b64}" type="{mime}">
    </audio>
    <script>
      (function(){{
        const el = document.getElementById("faah{nonce}");
        if(!el) return;
        const p = el.play();
        if(p && p.catch) p.catch(()=>{{}});
      }})();
    </script>
    """
    components.html(html, height=0, width=0)

# =============================
# Meme + slang + IG pack
# =============================
HINGLISH_PHRASES = {
    "kya scene": "What’s the plan / what’s going on?",
    "scene kya hai": "What’s the status?",
    "kya chal raha": "What’s up?",
    "kya haal": "How are things?",
    "chill maar": "Relax / don’t stress.",
    "set hai": "Confirmed / fixed.",
    "jugaad": "Quick workaround / hack.",
    "chalta hai": "It’s fine / let it slide.",
    "timepass": "Killing time / low-stakes fun.",
    "bhai": "Bro (friendly).",
    "yaar": "Mate/friend (friendly).",
    "pakka": "For sure / confirmed.",
    "sahi": "Nice / correct / legit.",
}

GENZ_SLANG = {
    "aura": "Vibe/energy; ‘aura points’ = cool points.",
    "cooked": "Overwhelmed / done for.",
    "brainrot": "Scroll-fried meme-brain vibe.",
    "delulu": "Playfully delusional optimism.",
    "rizz": "Charisma / flirting skill.",
    "cap": "Lie/exaggeration. ‘No cap’ = for real.",
    "bet": "Okay / agreed / say less.",
    "mid": "Mediocre.",
    "tea": "Gossip / truth / info.",
    "yap": "Talk a lot (playful).",
    "ick": "Tiny turn-off that ruins the vibe.",
    "soft launch": "Subtle relationship hint.",
    "hard launch": "Official relationship reveal.",
    "crash out": "Lose patience / snap (often joking).",
    "npc": "Autopilot energy.",
    "ate": "Nailed it.",
    "locked in": "Focused now.",
}

IG_TRENDS_LAST_UPDATED = "2026-02-28"
IG_TRENDS_PACK = {
    "reels": [
        "Hook fast (first ~1–2 seconds) with on-screen text.",
        "Micro-drama / educational storytelling beats random dancing.",
        "Value + BTS + clarity; sound-off friendly captions still matter.",
        "POV and partner-POV formats stay strong.",
        "CapCut-template style edits (transitions, timing) are common.",
        "Green-screen commentary / reaction formats are easy wins.",
    ],
    "formats": [
        "In vs Out (2026 edition)",
        "This vs That (quick contrast)",
        "POV: <hyper-specific situation>",
        "Green screen: reacting to ‘the moment’",
        "AI-replace scene gag (e.g., Tokyo Drift swap)",
    ],
    "posting": [
        "Use vertical 9:16 (1080×1920) for Reels.",
        "Mix Reels + carousels + stories to avoid fatigue.",
    ],
}

BOLLYWOOD_MEME_STYLES = [
    "Filmy entry + dramatic background score energy",
    "Overacting level: 100 (for no reason)",
    "‘Dialogues’ mode: ON, logic: OFF",
    "Slow zoom reaction + ‘abey yaar’",
    "Auntie network breaking news vibe",
]

def slang_lookup(term: str) -> str:
    key = (term or "").strip().lower()
    if not key:
        return "Use: /slang <word>  (e.g., /slang cooked)"
    if key in GENZ_SLANG:
        return f"{key}: {GENZ_SLANG[key]}"
    if key in ("no cap", "nocap"):
        return "no cap: For real / not lying."
    return "Not in my slang list yet—try another word."

def hinglish_lookup(term: str) -> str:
    key = (term or "").strip().lower()
    if not key:
        return "Use: /hindi <phrase>  (e.g., /hindi kya scene)"
    hits = [(k, v) for k, v in HINGLISH_PHRASES.items() if key in k]
    if not hits:
        return "Not found—try shorter (e.g., ‘scene’, ‘set’, ‘jugaad’)."
    return "\n".join([f"{k}: {v}" for k, v in hits[:15]])

def format_ig_pack(section: str) -> str:
    section = (section or "").lower().strip()
    if section in ("trends", "all", ""):
        out = []
        for k in ("reels", "formats", "posting"):
            out.append(f"IG {k.title()} (as of {IG_TRENDS_LAST_UPDATED}):\n- " + "\n- ".join(IG_TRENDS_PACK[k]))
        out.append("Try: /ig prompts  (to get copy-paste prompts)")
        return "\n\n".join(out)
    if section == "prompts":
        return (
            "Copy-paste prompts:\n"
            "- /meme pov about ‘I said on my way’\n"
            "- /meme invsout about college life\n"
            "- /meme thisvsthat about gym vs sleep\n"
            "- /meme greenscreen about ‘group chat drama’\n"
            "- /meme capcut about ‘weekend recap’\n"
            "- /meme aitokyo about ‘meeting reschedule’\n"
        )
    if section in IG_TRENDS_PACK:
        return f"IG {section.title()} (as of {IG_TRENDS_LAST_UPDATED}):\n- " + "\n- ".join(IG_TRENDS_PACK[section])
    return "Use: /ig trends | /ig reels | /ig formats | /ig posting | /ig prompts"

# =============================
# Meme engines
# =============================
TOPIC_KEYS = {
    "plans": {"plan","weekend","tomorrow","today","hangout","meet","movie","cafe","party"},
    "relationships": {"crush","date","dating","ghost","seen","reply","situationship","relationship","texting"},
    "study": {"exam","test","assignment","class","study","notes","college","school"},
    "food": {"momos","chai","coffee","pizza","burger","snack","craving","food","spicy"},
    "gym": {"gym","workout","protein","leg","cardio","training"},
    "social": {"reel","reels","story","post","caption","soft","hard","launch","instagram","ig"},
    "work": {"manager","client","standup","ppt","deck","deadline","meeting","call"},
    "mood": {"sad","tired","stressed","anxious","overthinking","burnt","low","happy"},
}

def detect_topic(text: str) -> str:
    tokens = set(re.findall(r"[a-z']+", (text or "").lower()))
    best = ("general", 0)
    for topic, keys in TOPIC_KEYS.items():
        score = len(tokens & keys)
        if score > best[1]:
            best = (topic, score)
    return best[0]

def hashtags(topic: str) -> str:
    base = {
        "plans": ["#weekendplans", "#friends", "#hangout"],
        "relationships": ["#situationship", "#texting", "#iykyk"],
        "study": ["#studentlife", "#examseason", "#studygram"],
        "food": ["#foodie", "#snacktime", "#streetfood"],
        "gym": ["#gymarc", "#fitness", "#legday"],
        "social": ["#reels", "#memes", "#captionideas"],
        "work": ["#workmemes", "#officehumor", "#consultinglife"],
        "mood": ["#mood", "#relatable", "#selfcare"],
        "general": ["#relatable", "#memes", "#vibes"],
    }
    return " ".join(base.get(topic, base["general"])[:8])

def make_caption(core: str, topic: str) -> str:
    hooks = ["POV:", "Me:", "Lowkey", "Highkey", "It’s giving", "Normalize"]
    specifics = ["at 2:13am", "with 3% battery", "after one chai", "during exam week", "in the group chat"]
    prompts = ["Real or nah.", "IYKYK.", "Be honest.", "Tell me I’m not alone."]
    core = re.sub(r"\s+", " ", (core or "")).strip()
    core = core[:110] if core else "this whole situation"
    return f"{random.choice(hooks)} {core} {random.choice(specifics)} {random.choice(prompts)}\n{hashtags(topic)}"

def make_faah_meme_text(core: str) -> str:
    core = re.sub(r"\s+", " ", (core or "")).strip() or "I try a tiny shortcut"
    setups = [f"Me: {core}", f"POV: {core}", f"When {core}"]
    payoff = random.choice([
        "Reality: FAAH (instant consequences)",
        "Universe: FAAH (same-day delivery)",
        "My luck: FAAH (plot twist unlocked)",
    ])
    return f"{random.choice(setups)}\n{payoff}"

MEME_FORMATS = {
    "pov": [
        "POV: {setup}\nText on screen: “why am I like this”\nCut to: {payoff}",
        "POV: {setup}\nMe (internally): “chill”\nAlso me: {payoff}",
    ],
    "microdrama": [
        "Hook: {setup}\nTwist: {payoff}\nCTA: ‘comment your version’",
        "Hook: {setup}\nEscalation: {payoff}\nCTA: ‘send this to your friend’",
    ],
    "invsout": [
        "IN: {setup}\nOUT: {payoff}",
        "IN: {setup}\nOUT: {payoff}\nNo cap.",
    ],
    "thisvsthat": [
        "This: {setup}\nThat: {payoff}",
        "{setup} vs {payoff}\nChoose your fighter.",
    ],
    "greenscreen": [
        "Green screen: {setup}\nMe: “let’s unpack this”\nAlso me: {payoff}",
        "Green screen: {setup}\nMy face says it all.\n{payoff}",
    ],
    "capcut": [
        "CapCut-template vibes:\nClip 1: {setup}\nBeat drop: {payoff}\nEnd card: ‘save for later’",
        "Fast cuts + on-beat text:\n{setup}\n{payoff}\nLoop it.",
    ],
    "aitokyo": [
        "AI Tokyo Drift swap:\nReplace the ‘car’ with: {setup}\nReplace the ‘drift’ with: {payoff}",
        "AI scene replace:\nSwap main character with: {setup}\nPlot twist: {payoff}",
    ],
    "bolly": [
        "Bollywood meme energy: {style}\nScene: {setup}\nReaction: {payoff}",
        "Filmy zoom-in:\n{style}\n{setup}\n{payoff}",
    ],
}

TOPIC_FILLERS = {
    "plans": (["‘Aaj early night’ bolna", "‘Kal pakka time pe’ kehna", "‘Just one drink’ promise karna"],
              ["2am tak ‘one last place’", "‘Location bhej’ pe 47 mins", "Morning me ‘I’m cooked’"]),
    "relationships": (["‘I’m not attached’ bolna", "‘Reply in 5 mins’ sochna", "‘Seen’ ko ignore karna"],
                      ["3 hours spiral", "‘Good night’ ke baad 12 reels", "‘We should talk’ drop"]),
    "study": (["‘Bas 20 mins padhai’ bolna", "Notes open = motivation 0", "Exam se 1 din pehle confidence"],
              ["3 tabs + 0 pages", "Aesthetic notes, tragic marks", "All-nighter delulu"]),
    "food": (["‘Diet Monday’ bolna", "‘Bas ek bite’ kehna", "Food app ‘sirf dekhne’"],
             ["Extra cheese + regret", "Extra spicy choose", "UPI pin speedrun"]),
    "gym": (["‘Leg day’ commitment", "Warm-up ke baad confidence", "Protein shake influencer arc"],
            ["Stairs enemy", "5 min workout, 50 min selfies", "‘Kal pakka’ loop"]),
    "social": (["Caption ‘simple sa’", "Soft launch subtle plan", "Story ‘lowkey’"],
               ["17 drafts", "Close friends chaos", "Delete → repost cycle"]),
    "work": (["Manager: ‘quick update?’", "Client: ‘small change’", "Standup: ‘any blockers?’"],
             ["PPT is my personality now", "Deadline jump-scare", "My soul left the call"]),
    "mood": (["‘I’m fine’ bolna", "Productive day plan", "Overthinking = ‘analysis’"],
             ["Bed + doomscroll", "To-do list: 12 | done: vibes", "Brain: FAAH"]),
    "general": (["Life ka plan", "Main character moment", "‘Bas ek kaam’"],
                ["Plot twist unlocked", "Aura points -10", "Chalta hai cope mode"]),
}

def _pick_setup_payoff(topic: str, core: str) -> tuple[str, str]:
    topic = topic if topic in TOPIC_FILLERS else "general"
    setups, payoffs = TOPIC_FILLERS[topic]
    setup = re.sub(r"\s+", " ", (core or "")).strip() or random.choice(setups)
    payoff = random.choice(payoffs)
    return setup, payoff

def make_meme(format_key: str, user_core: str) -> str:
    topic = detect_topic(user_core)
    setup, payoff = _pick_setup_payoff(topic, user_core)

    key = (format_key or "").strip().lower()
    if key not in MEME_FORMATS:
        key = "pov"

    template = random.choice(MEME_FORMATS[key])

    if key == "bolly":
        style = random.choice(BOLLYWOOD_MEME_STYLES)
        return template.format(style=style, setup=setup, payoff=payoff)

    return template.format(setup=setup, payoff=payoff)

# =============================
# Sound logic (single “error in between”)
# =============================
DEFAULT_SOUND_ERROR = "SoundBlockedError: click ‘Enable Sound’ once, then send again."

def maybe_queue_faah(trigger_text: str, must_play: bool, sound_mode: str, autoplay: bool, error_text: str):
    """
    must_play: True when user explicitly asked for FAAH (e.g., /faah or includes 'faah')
    """
    if not must_play:
        return

    # If user wants autoplay but hasn't enabled sound, show ONE helpful error
    if autoplay and (not st.session_state.sound_enabled) and (not st.session_state.sound_error_once):
        st.session_state.sound_error_once = True
        st.error(error_text or DEFAULT_SOUND_ERROR)

    # Choose bytes source
    if sound_mode == "FAAH (uploaded)" and st.session_state.faah_upload_bytes:
        queue_audio(
            st.session_state.faah_upload_bytes,
            st.session_state.faah_upload_mime or "audio/mpeg",
            label="FAAH",
            autoplay=autoplay,
        )
        return

    if sound_mode == "FAAH (assets)" and ASSET_BYTES:
        queue_audio(ASSET_BYTES, ASSET_MIME or "audio/mpeg", label=f"FAAH ({ASSET_PATH})", autoplay=autoplay)
        return

    if sound_mode == "FAAH (synth)":
        queue_audio(make_faah_synth_wav(), "audio/wav", label="FAAH (synth)", autoplay=autoplay)
        return

    # Fallback
    queue_audio(make_faah_synth_wav(), "audio/wav", label="FAAH (fallback synth)", autoplay=autoplay)

# =============================
# Bot reply router
# =============================
def bot_reply(user_text: str) -> str:
    t = (user_text or "").strip()
    low = t.lower()

    if low in ("/help", "help"):
        return (
            "Type these commands:\n"
            "- /faah  (play sound)\n"
            "- /meme <pov|microdrama|invsout|thisvsthat|greenscreen|capcut|aitokyo|bolly> <text>\n"
            "- /caption <text>\n"
            "- /ig trends|prompts|reels|formats|posting\n"
            "- /slang <word>\n"
            "- /hindi <phrase>\n\n"
            "Examples:\n"
            "- /faah\n"
            "- /meme pov I said ‘on my way’\n"
            "- /meme microdrama client said ‘small change’\n"
            "- /meme invsout college life\n"
            "- /meme greenscreen group chat drama\n"
            "- /meme capcut weekend recap\n"
            "- /meme aitokyo meeting reschedule\n"
            "- /meme bolly when chai finishes\n"
        )

    if low.startswith("/ig"):
        arg = t[len("/ig"):].strip() or "trends"
        return format_ig_pack(arg)

    if low.startswith("/slang"):
        return slang_lookup(t[len("/slang"):])

    if low.startswith("/hindi"):
        return hinglish_lookup(t[len("/hindi"):])

    if low.startswith("/caption"):
        topic = detect_topic(t)
        return make_caption(t[len("/caption"):].strip(), topic)

    if low.startswith("/meme"):
        rest = t[len("/meme"):].strip()
        parts = rest.split(maxsplit=1)
        fmt = parts[0].lower() if parts else "pov"
        core = parts[1] if len(parts) > 1 else ""
        if "faah" in rest.lower():
            core2 = re.sub(r"\bfaah\b", "", core, flags=re.I).strip()
            return "FAAH meme (text):\n" + make_faah_meme_text(core2)
        return make_meme(fmt, core)

    if low.startswith("/faah"):
        return "FAAH triggered."

    # Default conversational nudge + a suggested command
    topic = detect_topic(t)
    prompts = {
        "work": "Try: /meme microdrama client said ‘small change’",
        "social": "Try: /ig prompts or /meme greenscreen group chat drama",
        "study": "Try: /caption exam week survival",
        "food": "Try: /meme bolly when momos are extra spicy",
        "relationships": "Try: /meme pov ‘I’m not attached’",
        "general": "Try: /meme pov your situation",
    }
    return f"Tell me the exact situation in one line. {prompts.get(topic, prompts['general'])}"

# =============================
# Sidebar
# =============================
with st.sidebar:
    st.subheader("Sound")

    sound_mode = st.radio(
        "Mode",
        ["Off", "FAAH (uploaded)", "FAAH (assets)", "FAAH (synth)"],
        index=1,
    )
    autoplay = st.toggle("Attempt autoplay", value=True)
    error_text = st.text_input("One-time sound error text", value=DEFAULT_SOUND_ERROR)

    colA, colB = st.columns(2)
    with colA:
        if st.button("Enable Sound (click once)"):
            st.session_state.sound_enabled = True
            st.success("Enabled. Autoplay will be attempted.")
    with colB:
        if st.button("Reset sound error"):
            st.session_state.sound_error_once = False
            st.info("Sound error will show once again.")

    if sound_mode == "FAAH (uploaded)":
        up = st.file_uploader("Upload faah.mp3 or faah.wav", type=["mp3", "wav"])
        if up is not None:
            st.session_state.faah_upload_bytes = up.getvalue()
            st.session_state.faah_upload_name = up.name
            st.session_state.faah_upload_mime = up.type or ("audio/mpeg" if up.name.lower().endswith(".mp3") else "audio/wav")

        c1, c2 = st.columns(2)
        with c1:
            if st.button("Preview FAAH"):
                if st.session_state.faah_upload_bytes:
                    st.audio(st.session_state.faah_upload_bytes, format=st.session_state.faah_upload_mime or "audio/mpeg")
                else:
                    st.warning("Upload the MP3 first.")
        with c2:
            if st.button("Clear upload"):
                st.session_state.faah_upload_bytes = None
                st.session_state.faah_upload_mime = None
                st.session_state.faah_upload_name = None

        if st.session_state.faah_upload_name:
            st.caption(f"Loaded: {st.session_state.faah_upload_name}")

    if sound_mode == "FAAH (assets)":
        if ASSET_BYTES:
            st.caption(f"Loaded from repo: {ASSET_PATH}")
            if st.button("Preview assets FAAH"):
                st.audio(ASSET_BYTES, format=ASSET_MIME or "audio/mpeg")
        else:
            st.warning("Not found: assets/faah.mp3 (or faah.wav).")

    st.divider()
    st.subheader("Quick inputs")
    if st.button("Play FAAH now"):
        st.session_state._queued_input = "/faah"
    if st.button("FAAH meme: extra spicy momos"):
        st.session_state._queued_input = "/meme faah about extra spicy momos"
    if st.button("Latest IG formats pack"):
        st.session_state._queued_input = "/ig trends"
    if st.button("Bollywood-style meme"):
        st.session_state._queued_input = "/meme bolly when chai finishes"

    st.divider()
    st.caption("Tip: If autoplay is blocked, click Enable Sound once.")

# =============================
# Hero
# =============================
st.markdown(
    """
<div class="hero">
  <div class="title">FAAH • Insta Meme Bot (Hinglish + Bollywood)</div>
  <div class="sub">
    <span class="kbd">/faah</span>
    <span class="kbd">/meme</span>
    <span class="kbd">/ig</span>
    <span class="kbd">/caption</span>
    <span class="kbd">/slang</span>
    <span class="kbd">/hindi</span>
    <span class="kbd">/help</span>
  </div>
  <div class="chips">
    <div class="chip">Try: /faah</div>
    <div class="chip">Try: /meme pov I said ‘on my way’</div>
    <div class="chip">Try: /meme invsout college life</div>
    <div class="chip">Try: /meme greenscreen group chat drama</div>
    <div class="chip">Try: /meme bolly when chai finishes</div>
  </div>
</div>
""",
    unsafe_allow_html=True,
)

# =============================
# Stable audio render (attempt autoplay + always show player)
# =============================
if st.session_state.pending_audio_bytes is not None:
    if st.session_state.pending_audio_label:
        st.caption(st.session_state.pending_audio_label)

    mime = st.session_state.pending_audio_mime or "audio/mpeg"

    # Best-effort autoplay only if user enabled sound
    if autoplay and st.session_state.pending_audio_autoplay and st.session_state.sound_enabled:
        render_autoplay_audio(st.session_state.pending_audio_bytes, mime, st.session_state.audio_nonce)

    # Always show fallback player
    st.audio(st.session_state.pending_audio_bytes, format=mime)

    # clear
    st.session_state.pending_audio_bytes = None
    st.session_state.pending_audio_mime = None
    st.session_state.pending_audio_label = None
    st.session_state.pending_audio_autoplay = True

# =============================
# Chat card
# =============================
st.markdown('<div class="card">', unsafe_allow_html=True)
st.markdown('<div class="small">Type a command, or describe a situation in one line.</div>', unsafe_allow_html=True)

for m in st.session_state.messages:
    with st.chat_message(m["role"]):
        st.markdown(m["content"])
        st.markdown(f'<div class="small">{m["ts"]}</div>', unsafe_allow_html=True)

queued = st.session_state._queued_input
if queued:
    st.session_state._queued_input = None

user_text = queued or st.chat_input("Type here… (try: /faah)")

st.markdown("</div>", unsafe_allow_html=True)

# =============================
# Handle message
# =============================
if user_text:
    ts = dt.datetime.now().strftime("%H:%M")
    st.session_state.messages.append({"role": "user", "content": user_text, "ts": ts})

    if is_blocked(user_text):
        st.session_state.messages.append({"role": "assistant", "content": SAFE_REFUSAL, "ts": ts})
        queue_audio(make_beep_wav(), "audio/wav", label="Beep", autoplay=False)
        st.rerun()

    reply = bot_reply(user_text)

    # FAAH triggers (guaranteed trigger if user says /faah or includes 'faah')
    low = (user_text or "").lower()
    must_play = low.startswith("/faah") or (" faah" in f" {low}") or low.startswith("/meme faah")

    if sound_mode != "Off":
        maybe_queue_faah(
            trigger_text=user_text,
            must_play=must_play,
            sound_mode=sound_mode,
            autoplay=autoplay,
            error_text=error_text,
        )

    st.session_state.messages.append({"role": "assistant", "content": reply, "ts": ts})
    st.rerun()
